"use client";

import React, { createContext, useCallback, useContext, useMemo, useState } from "react";

type Locale = "vi" | "en";
type Messages = Record<string, string>;
type Dictionary = Record<Locale, Messages>;

const messages: Dictionary = {
  vi: {
    nav_features: "Tính năng",
    nav_pricing: "Bảng giá",
    nav_target: "Đối tượng",
    nav_team: "Đội ngũ",
    nav_achievement: "Thành tựu",
    nav_contact: "Liên hệ",
    nav_newspaper: "Báo chí",
    nav_cost: "Tối ưu chi phí",
    nav_menu: "Menu điều hướng",
    nav_dashboard: "Vào Dashboard",
    nav_user: "Tài khoản",
    settings_title: "Cài đặt",
    auth_logout: "Đăng xuất",
    try_free: "Dùng thử miễn phí",
    contact_sales: "Liên hệ tư vấn",
    login: "Đăng nhập",
    hero_cta_hint: "Không cần thẻ. Dùng ngay trong vài giây.",
    hero_trust: "Được báo chí & đối tác tin tưởng",
    survey_modal_title: "Đăng ký trải nghiệm Lawzy",
    survey_close: "Đóng form",
    survey_loading: "Đang chuẩn bị form...",
    hero_badge: "Miễn phí $20 credit Lawzy AI dành cho 100 người dùng đầu tiên",
    hero_title_1: "Lawzy - Legal Tech Startup tiên phong tại Việt Nam",
    hero_title_2: "Bridging the legal gap",
    hero_title_2_options: "Bridging the legal gap|Kết nối pháp lý và vận hành|Mở rộng năng lực pháp lý cho mọi tổ chức",
    hero_subtitle: "Lawzy xây dựng hệ sinh thái sản phẩm pháp lý số, giúp doanh nghiệp và hãng luật vận hành hiệu quả hơn trong kỷ nguyên AI.",
    hero_cta_clm: "Khám phá Contract Lifecycle Management",
    hero_cta_lpms: "Khám phá Legal Practice Management",
    products_title: "Hai sản phẩm chủ lực của Lawzy",
    products_subtitle: "Từ doanh nghiệp SME đến law firm, Lawzy cung cấp nền tảng phù hợp cho từng mô hình vận hành pháp lý.",
    product_badge: "Lawzy Product",
    product_cta: "Xem chi tiết",
    product_clm_title: "Contract Lifecycle Management",
    product_clm_description: "Hệ thống quản lý vòng đời hợp đồng cho doanh nghiệp, từ soạn thảo đến ký kết và theo dõi nghĩa vụ.",
    product_clm_audience: "Phù hợp cho SMEs, phòng pháp chế, Admin, Sales và Ops.",
    product_clm_page_subtitle: "Nền tảng CLM của Lawzy giúp doanh nghiệp chuẩn hóa quy trình hợp đồng, kiểm soát rủi ro và tăng tốc vận hành liên phòng ban.",
    product_lpms_title: "Legal Practice Management System",
    product_lpms_description: "Hệ thống quản lý/chuyển đổi số cho law firm và lawyers, tập trung hồ sơ vụ việc, quy trình và hiệu suất đội ngũ.",
    product_lpms_audience: "Phù hợp cho law firm, luật sư và đội ngũ trợ lý pháp lý.",
    product_lpms_page_subtitle: "LPMS của Lawzy hỗ trợ law firm số hóa vận hành, quản lý công việc pháp lý theo chuẩn và nâng cao hiệu suất cộng tác của đội ngũ.",
    product_back_home: "Quay lại trang chủ",
    lpms_highlights_title: "Năng lực chính của LPMS",
    lpms_highlights_subtitle: "Thiết kế cho môi trường hành nghề luật hiện đại, nơi dữ liệu, quy trình và cộng tác cần đồng bộ.",
    lpms_highlight_1_title: "Chuẩn hóa quy trình nghiệp vụ",
    lpms_highlight_1_desc: "Thiết lập luồng xử lý vụ việc, phân công công việc và theo dõi tiến độ theo từng giai đoạn.",
    lpms_highlight_2_title: "Quản trị hồ sơ pháp lý tập trung",
    lpms_highlight_2_desc: "Lưu trữ và truy xuất tài liệu, biểu mẫu, lịch sử xử lý và dữ liệu khách hàng trên cùng một nền tảng.",
    lpms_highlight_3_title: "Tăng hiệu suất vận hành law firm",
    lpms_highlight_3_desc: "Giảm thao tác thủ công, tăng khả năng phối hợp giữa luật sư và trợ lý, cải thiện trải nghiệm khách hàng.",
    features_title: "Tính năng giúp bạn làm việc thông minh hơn",
    features_title_highlight: "thông minh hơn",
    features_subtitle: "Từ soạn thảo đến ký kết. AI đồng hành ở mọi bước. Giảm rủi ro, tăng hiệu quả.",
    feature_card1_title: "Soạn thảo hợp đồng dễ dàng",
    feature_card1_desc: "Tạo hợp đồng chuyên nghiệp trong vài phút với các mẫu có sẵn và gợi ý AI thông minh.",
    feature_card2_title: "Rà soát rủi ro tự động",
    feature_card2_desc: "AI phân tích và cảnh báo các điều khoản bất lợi, giúp bạn ký kết an toàn hơn.",
    feature_card3_title: "Quản lý hợp đồng tập trung",
    feature_card3_desc: "Theo dõi trạng thái, nhắc nhở nghĩa vụ và lưu trữ an toàn mọi hợp đồng của bạn.",
    target_title: "Dành cho đội ngũ pháp lý và vận hành",
    target_title_highlight: "pháp lý",
    target_subtitle: "Chuẩn hoá quy trình, giảm bottleneck phê duyệt và quản lý hợp đồng xuyên phòng ban trong một nơi.",
    target_sme_title: "Doanh nghiệp vừa và nhỏ (SME)",
    target_sme_desc: "Tối ưu quy trình, giảm chi phí pháp lý và quản lý hợp đồng hiệu quả mà không cần phòng pháp chế riêng.",
    target_sme_feat1: "Tiết kiệm chi phí thuê luật sư",
    target_sme_feat2: "Giảm thiểu rủi ro pháp lý",
    target_sme_feat3: "Quản lý tập trung, dễ dàng tra cứu",
    target_legal_title: "Đội ngũ pháp lý & Nhân sự",
    target_legal_desc: "Công cụ đắc lực giúp rà soát nhanh, chuẩn hóa quy trình và giảm tải khối lượng công việc lặp lại.",
    target_legal_feat1: "Rà soát hợp đồng tự động",
    target_legal_feat2: "Chuẩn hóa mẫu hợp đồng",
    target_legal_feat3: "Tăng năng suất làm việc",
    achievement_title: "Được công nhận",
    achievement_title_highlight: "Được công nhận",
    achievement_item_title: "Giải nhì Cuộc thi Khởi nghiệp và Đổi mới sáng tạo TP.HCM 2025",
    members_title: "Đội ngũ phát triển",
    member_thu_role: "Trưởng nhóm / Quản lý sản phẩm",
    member_quan_ly_role: "Kỹ sư phần mềm",
    member_quan_huynh_role: "Kỹ sư phần mềm",
    newspaper_title: "Lawzy trên báo chí",
    newspaper_title_highlight: "Lawzy",
    blog_section_title: "Tin tức & Bài viết",
    blog_section_subtitle: "Cập nhật tin tức, kiến thức pháp lý và thông báo mới từ Lawzy",
    blog_view_all: "Xem tất cả",
    incubation_by: "Được ươm tạo bởi",
    investors_title: "Nhà đầu tư & Vườn ươm",
    investors_title_highlight: "Nhà đầu tư & Vườn ươm",
    investors_subtitle: "Những quỹ và đối tác đồng hành cùng Lawzy.",
    footer_contact: "Liên hệ",
    footer_tagline: "An tâm. Kịp thời. Đồng hành cùng bạn",
    footer_description: "Lawzy phát triển các sản phẩm legal tech cho doanh nghiệp và law firm, với tầm nhìn Bridging the legal gap.",
    footer_column_product: "Sản phẩm",
    footer_column_legal: "Pháp lý",
    footer_link_features: "Tính năng",
    footer_link_pricing: "Bảng giá",
    footer_link_cost: "Tối ưu chi phí",
    footer_link_audience: "Đối tượng phù hợp",
    footer_link_press: "Báo chí",
    footer_link_achievements: "Thành tựu",
    footer_link_news: "Tin tức",
    footer_register: "Đăng ký",
    footer_address: "TP. Hồ Chí Minh, Việt Nam",
    footer_rights: "Bảo lưu mọi quyền.",
    footer_privacy: "Chính sách bảo mật",
    footer_terms: "Điều khoản sử dụng",
    language_english: "EN",
    language_vietnamese: "VI",
    cost_title: "Ít công cụ hơn, ít chi phí hơn",
    cost_title_highlight: "ít chi phí hơn",
    cost_subtitle: "Loại bỏ phần mềm thừa. Giữ đội ngũ nhanh, rõ ràng và kết nối.",
    cost_stat_efficiency: "10",
    cost_stat_efficiency_label: "hiệu quả vận hành",
    cost_stat_productivity: "39",
    cost_stat_productivity_label: "năng suất cao hơn",
    cost_stat_savings: "70",
    cost_stat_savings_label: "tiết kiệm chi phí",
    cost_stats_note: "Số liệu tham chiếu từ nghiên cứu thị trường legal tech.",
    pricing_section_title: "Bảng giá",
    pricing_section_subtitle: "Chọn gói phù hợp với nhu cầu của bạn. Nâng cấp bất cứ lúc nào.",
    payment_billing_monthly: "Tháng",
    payment_billing_yearly: "Năm",
    pricing_no_monthly_plans: "Chưa có gói theo tháng.",
    pricing_no_yearly_plans: "Chưa có gói theo năm.",
    contact_modal_title: "Đặt lịch tư vấn miễn phí",
    contact_modal_subtitle: "Đặt lịch tư vấn 1-1 về giải pháp Lawzy và nhận báo giá phù hợp với doanh nghiệp của bạn.",
    contact_modal_benefit_1: "Phản hồi trong 24 giờ",
    contact_modal_benefit_2: "Tư vấn miễn phí, không ràng buộc",
    contact_modal_close: "Đóng",
    contact_modal_success: "Gửi thành công!",
    contact_modal_success_desc: "Chúng tôi sẽ liên hệ bạn trong thời gian sớm nhất.",
    contact_modal_error: "Có lỗi xảy ra. Vui lòng thử lại.",
    contact_modal_retry: "Thử lại",
    contact_modal_name: "Họ tên",
    contact_modal_name_placeholder: "Nguyễn Văn A",
    contact_modal_email: "Email",
    contact_modal_email_placeholder: "email@company.com",
    contact_modal_phone: "Số điện thoại",
    contact_modal_phone_placeholder: "+84",
    contact_modal_company: "Công ty",
    contact_modal_company_placeholder: "Công ty cổ phần Lawzy",
    contact_modal_message: "Nội dung",
    contact_modal_message_placeholder: "Bạn cần hỗ trợ gì?",
    contact_modal_submit: "Đặt lịch ngay",
    contact_modal_cancel: "Hủy",
    contact_modal_sending: "Đang gửi...",
    contact_validation_name: "Vui lòng nhập họ tên (ít nhất 2 ký tự)",
    contact_validation_email: "Vui lòng nhập email",
    contact_validation_email_invalid: "Vui lòng nhập đúng định dạng email",
    contact_validation_phone: "Vui lòng nhập số điện thoại hợp lệ",
    floating_back_to_top: "Về đầu trang",
    floating_book_demo: "Đặt lịch demo",
    contact_page_title: "Liên hệ Lawzy",
    contact_page_subtitle: "Để lại thông tin, đội ngũ chúng tôi sẽ phản hồi trong thời gian sớm nhất.",
    contact_page_back: "Về trang chủ",
    contact_page_note: "Chúng tôi cam kết phản hồi trong vòng 24 giờ làm việc.",
  },
  en: {
    nav_features: "Features",
    nav_pricing: "Pricing",
    nav_target: "Target",
    nav_team: "Team",
    nav_achievement: "Achievements",
    nav_contact: "Contact",
    nav_newspaper: "Press",
    nav_cost: "Cost savings",
    nav_menu: "Navigation menu",
    nav_dashboard: "Dashboard",
    nav_user: "Account",
    settings_title: "Settings",
    auth_logout: "Log out",
    try_free: "Try for free",
    contact_sales: "Contact sales",
    login: "Log in",
    survey_modal_title: "Register for Lawzy early access",
    survey_close: "Close form",
    survey_loading: "Preparing the form...",
    hero_badge: "Free $20 Lawzy AI credit for the first 100 users",
    hero_title_1: "Lawzy - One of Vietnam's early Legal Tech Startups",
    hero_title_2: "Bridging the legal gap",
    hero_title_2_options: "Bridging the legal gap|Connecting legal and operations|Scaling legal capability for every team",
    hero_subtitle: "Lawzy builds a digital legal product ecosystem that helps businesses and law firms operate better in the AI era.",
    hero_cta_clm: "Explore Contract Lifecycle Management",
    hero_cta_lpms: "Explore Legal Practice Management",
    products_title: "Lawzy's two core products",
    products_subtitle: "From SMEs to law firms, Lawzy provides products tailored to each legal operating model.",
    product_badge: "Lawzy Product",
    product_cta: "View details",
    product_clm_title: "Contract Lifecycle Management",
    product_clm_description: "An end-to-end contract lifecycle system for businesses, from drafting to signing and obligation tracking.",
    product_clm_audience: "Built for SMEs, legal teams, admins, sales and operations.",
    product_clm_page_subtitle: "Lawzy CLM helps businesses standardize contract workflows, control risk, and speed up cross-functional execution.",
    product_lpms_title: "Legal Practice Management System",
    product_lpms_description: "A digitization and management platform for law firms and lawyers, centralizing matters, workflows and team productivity.",
    product_lpms_audience: "Built for law firms, lawyers, and legal assistants.",
    product_lpms_page_subtitle: "Lawzy LPMS enables law firms to digitize operations, manage legal work systematically, and improve collaboration efficiency.",
    product_back_home: "Back to home",
    lpms_highlights_title: "Core LPMS capabilities",
    lpms_highlights_subtitle: "Designed for modern legal practice, where data, process and collaboration must stay aligned.",
    lpms_highlight_1_title: "Standardized practice workflows",
    lpms_highlight_1_desc: "Define matter workflows, assign tasks clearly, and track progress across every legal stage.",
    lpms_highlight_2_title: "Centralized legal matter management",
    lpms_highlight_2_desc: "Store and retrieve documents, templates, handling history, and client data in one place.",
    lpms_highlight_3_title: "Higher law firm operating efficiency",
    lpms_highlight_3_desc: "Reduce manual work, improve lawyer-assistant coordination, and deliver better client experience.",
    hero_cta_hint: "No credit card required. Get started in seconds.",
    hero_trust: "Trusted by press & partners",
    features_title: "Features that make you work smarter",
    features_title_highlight: "smarter",
    features_subtitle: "From drafting to signing. AI at every step. Reduce risk, increase efficiency.",
    feature_card1_title: "Draft contracts effortlessly",
    feature_card1_desc: "Create professional contracts in minutes with ready-made templates and smart AI suggestions.",
    feature_card2_title: "Automated risk review",
    feature_card2_desc: "AI analyzes and flags unfavorable clauses, helping you sign with confidence.",
    feature_card3_title: "Centralized contract management",
    feature_card3_desc: "Track status, get obligation reminders, and store all your contracts securely.",
    target_title: "For legal and operations teams",
    target_title_highlight: "legal",
    target_subtitle: "Standardize workflows, remove approval bottlenecks, and manage cross-team contracts in one place.",
    target_sme_title: "SMEs & Startups",
    target_sme_desc: "Optimize processes, reduce legal costs, and manage contracts effectively without a dedicated legal department.",
    target_sme_feat1: "Save on lawyer fees",
    target_sme_feat2: "Minimize legal risks",
    target_sme_feat3: "Centralized management, easy lookup",
    target_legal_title: "Legal Teams & HR",
    target_legal_desc: "A powerful tool to speed up review, standardize processes, and reduce repetitive workload.",
    target_legal_feat1: "Automated contract review",
    target_legal_feat2: "Standardize contract templates",
    target_legal_feat3: "Increase productivity",
    achievement_title: "Recognized",
    achievement_title_highlight: "Recognized",
    achievement_item_title: "2nd Prize - Startup & Innovation Competition HCMC 2025",
    members_title: "Our Team",
    member_thu_role: "Leader / Product Manager",
    member_quan_ly_role: "Software Developer",
    member_quan_huynh_role: "Software Developer",
    newspaper_title: "Lawzy in the press",
    newspaper_title_highlight: "Lawzy",
    blog_section_title: "News & Articles",
    blog_section_subtitle: "Latest news, legal insights and updates from Lawzy",
    blog_view_all: "View all",
    incubation_by: "Incubated by",
    investors_title: "Investors & Incubators",
    investors_title_highlight: "Investors & Incubators",
    investors_subtitle: "Funds and partners backing Lawzy.",
    footer_contact: "Contact",
    footer_tagline: "Peace of mind. On time. By your side",
    footer_description: "Lawzy builds legal tech products for businesses and law firms, driven by the vision of Bridging the legal gap.",
    footer_column_product: "Product",
    footer_column_legal: "Legal",
    footer_link_features: "Features",
    footer_link_pricing: "Pricing",
    footer_link_cost: "Cost savings",
    footer_link_audience: "Who it's for",
    footer_link_press: "Press",
    footer_link_achievements: "Achievements",
    footer_link_news: "News",
    footer_register: "Sign up",
    footer_address: "Ho Chi Minh City, Vietnam",
    footer_rights: "All rights reserved.",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Use",
    language_english: "EN",
    language_vietnamese: "VI",
    cost_title: "Fewer tools, fewer costs",
    cost_title_highlight: "fewer costs",
    cost_subtitle: "Cut software bloat. Keep teams fast, clear, and connected.",
    cost_stat_efficiency: "10",
    cost_stat_efficiency_label: "operational efficiency",
    cost_stat_productivity: "39",
    cost_stat_productivity_label: "more productive",
    cost_stat_savings: "70",
    cost_stat_savings_label: "cost savings",
    cost_stats_note: "Reference figures from legal tech market research.",
    pricing_section_title: "Pricing",
    pricing_section_subtitle: "Choose the plan that fits your needs. Upgrade anytime.",
    payment_billing_monthly: "Monthly",
    payment_billing_yearly: "Yearly",
    pricing_no_monthly_plans: "No monthly plans available.",
    pricing_no_yearly_plans: "No yearly plans available.",
    contact_modal_title: "Book a demo",
    contact_modal_subtitle: "Schedule a 1:1 consultation on Lawzy and receive a tailored quote for your business.",
    contact_modal_benefit_1: "Response within 24 hours",
    contact_modal_benefit_2: "Free, no-obligation consultation",
    contact_modal_close: "Close",
    contact_modal_success: "Sent successfully!",
    contact_modal_success_desc: "We will contact you as soon as possible.",
    contact_modal_error: "Something went wrong. Please try again.",
    contact_modal_retry: "Retry",
    contact_modal_name: "Full name",
    contact_modal_name_placeholder: "John Doe",
    contact_modal_email: "Email",
    contact_modal_email_placeholder: "email@company.com",
    contact_modal_phone: "Phone",
    contact_modal_phone_placeholder: "+84",
    contact_modal_company: "Company",
    contact_modal_company_placeholder: "Lawzy Inc.",
    contact_modal_message: "Message",
    contact_modal_message_placeholder: "What do you need help with?",
    contact_modal_submit: "Book now",
    contact_modal_cancel: "Cancel",
    contact_modal_sending: "Sending...",
    contact_validation_name: "Please enter your full name (at least 2 characters)",
    contact_validation_email: "Please enter your email",
    contact_validation_email_invalid: "Please enter a valid email address",
    contact_validation_phone: "Please enter a valid phone number",
    floating_back_to_top: "Back to top",
    floating_book_demo: "Book a demo",
    contact_page_title: "Contact Lawzy",
    contact_page_subtitle: "Leave your details and our team will get back to you as soon as possible.",
    contact_page_back: "Back to home",
    contact_page_note: "We aim to respond within 24 business hours.",
  },
};

type I18nContextValue = {
  locale: Locale;
  t: (key: string) => string;
  setLocale: (locale: Locale) => void;
};

const I18nContext = createContext<I18nContextValue | null>(null);

export function LandingLanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("lawzy_lang") as Locale | null;
      if (stored === "en" || stored === "vi") return stored;
      return navigator.language.startsWith("vi") ? "vi" : "en";
    }
    return "vi";
  });

  const t = useCallback(
    (key: string) => messages[locale][key] ?? key,
    [locale]
  );

  const setLocale = useCallback((next: Locale) => {
    if (typeof window !== "undefined") localStorage.setItem("lawzy_lang", next);
    setLocaleState(next);
  }, []);

  const value = useMemo(() => ({ locale, t, setLocale }), [locale, t, setLocale]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const ctx = useContext(I18nContext);
  if (!ctx) throw new Error("useI18n must be used within LandingLanguageProvider");
  return ctx;
}
