"use client";

import React, { createContext, useCallback, useContext, useMemo, useState } from "react";

type Locale = "vi" | "en";
type Messages = Record<string, string>;
type Dictionary = Record<Locale, Messages>;

const messages: Dictionary = {
  vi: {
    nav_features: "Tính năng",
    nav_pricing: "Bảng giá",
    nav_target: "Đối tượng",
    nav_team: "Đội ngũ",
    nav_achievement: "Thành tựu",
    nav_contact: "Liên hệ",
    nav_newspaper: "Báo chí",
    nav_cost: "Tối ưu chi phí",
    nav_menu: "Menu điều hướng",
    nav_dashboard: "Vào Dashboard",
    nav_user: "Tài khoản",
    settings_title: "Cài đặt",
    auth_logout: "Đăng xuất",
    try_free: "Dùng thử miễn phí",
    contact_sales: "Liên hệ tư vấn",
    login: "Đăng nhập",
    hero_cta_hint: "Không cần thẻ. Dùng ngay trong vài giây.",
    hero_trust: "Được báo chí & đối tác tin tưởng",
    survey_modal_title: "Đăng ký trải nghiệm Lawzy",
    survey_close: "Đóng form",
    survey_loading: "Đang chuẩn bị form...",
    hero_badge: "Miễn phí $20 credit Lawzy AI dành cho 100 người dùng đầu tiên",
    hero_title_1: "Nền tảng hợp đồng AI cho",
    hero_title_2: "cho doanh nghiệp phát triển",
    hero_title_2_options: "cho doanh nghiệp phát triển|cho cá nhân|cho đội ngũ pháp lý|cho startup",
    hero_subtitle: "Trí tuệ tích hợp. Soạn thảo nhanh, phát hiện rủi ro sớm, quản lý mọi hợp đồng trong một nơi.",
    features_title: "Tính năng giúp bạn làm việc thông minh hơn",
    features_title_highlight: "thông minh hơn",
    features_subtitle: "Từ soạn thảo đến ký kết. AI đồng hành ở mọi bước. Giảm rủi ro, tăng hiệu quả.",
    feature_card1_title: "Soạn thảo hợp đồng dễ dàng",
    feature_card1_desc: "Tạo hợp đồng chuyên nghiệp trong vài phút với các mẫu có sẵn và gợi ý AI thông minh.",
    feature_card2_title: "Rà soát rủi ro tự động",
    feature_card2_desc: "AI phân tích và cảnh báo các điều khoản bất lợi, giúp bạn ký kết an toàn hơn.",
    feature_card3_title: "Quản lý hợp đồng tập trung",
    feature_card3_desc: "Theo dõi trạng thái, nhắc nhở nghĩa vụ và lưu trữ an toàn mọi hợp đồng của bạn.",
    target_title: "Dành cho cá nhân, cho đội nhóm, cho công ty",
    target_title_highlight: "cá nhân",
    target_subtitle: "Từ startup đến doanh nghiệp, từ freelance đến phòng pháp chế. Lawzy giúp mọi người ký kết an tâm.",
    target_sme_title: "Doanh nghiệp vừa và nhỏ (SME)",
    target_sme_desc: "Tối ưu quy trình, giảm chi phí pháp lý và quản lý hợp đồng hiệu quả mà không cần phòng pháp chế riêng.",
    target_sme_feat1: "Tiết kiệm chi phí thuê luật sư",
    target_sme_feat2: "Giảm thiểu rủi ro pháp lý",
    target_sme_feat3: "Quản lý tập trung, dễ dàng tra cứu",
    target_legal_title: "Đội ngũ pháp lý & Nhân sự",
    target_legal_desc: "Công cụ đắc lực giúp rà soát nhanh, chuẩn hóa quy trình và giảm tải khối lượng công việc lặp lại.",
    target_legal_feat1: "Rà soát hợp đồng tự động",
    target_legal_feat2: "Chuẩn hóa mẫu hợp đồng",
    target_legal_feat3: "Tăng năng suất làm việc",
    achievement_title: "Được công nhận",
    achievement_title_highlight: "Được công nhận",
    achievement_item_title: "Giải nhì Cuộc thi Khởi nghiệp và Đổi mới sáng tạo TP.HCM 2025",
    members_title: "Đội ngũ phát triển",
    member_thu_role: "Trưởng nhóm / Quản lý sản phẩm",
    member_quan_ly_role: "Kỹ sư phần mềm",
    member_quan_huynh_role: "Kỹ sư phần mềm",
    newspaper_title: "Lawzy trên báo chí",
    newspaper_title_highlight: "Lawzy",
    blog_section_title: "Tin tức & Bài viết",
    blog_section_subtitle: "Cập nhật tin tức, kiến thức pháp lý và thông báo mới từ Lawzy",
    blog_view_all: "Xem tất cả",
    incubation_by: "Được ươm tạo bởi",
    footer_contact: "Liên hệ",
    footer_tagline: "An tâm. Kịp thời. Đồng hành cùng bạn",
    footer_description: "Soạn thảo, rà soát và quản lý hợp đồng với AI. Dành cho doanh nghiệp và đội ngũ pháp lý.",
    footer_column_product: "Sản phẩm",
    footer_column_legal: "Pháp lý",
    footer_link_features: "Tính năng",
    footer_link_pricing: "Bảng giá",
    footer_link_cost: "Tối ưu chi phí",
    footer_link_audience: "Đối tượng phù hợp",
    footer_link_press: "Báo chí",
    footer_link_achievements: "Thành tựu",
    footer_link_news: "Tin tức",
    footer_register: "Đăng ký",
    footer_address: "TP. Hồ Chí Minh, Việt Nam",
    footer_rights: "Bảo lưu mọi quyền.",
    footer_privacy: "Chính sách bảo mật",
    footer_terms: "Điều khoản sử dụng",
    language_english: "EN",
    language_vietnamese: "VI",
    cost_title: "Ít công cụ hơn, ít chi phí hơn",
    cost_title_highlight: "ít chi phí hơn",
    cost_subtitle: "Loại bỏ phần mềm thừa. Giữ đội ngũ nhanh, rõ ràng và kết nối.",
    cost_stat_efficiency: "10",
    cost_stat_efficiency_label: "hiệu quả vận hành",
    cost_stat_productivity: "39",
    cost_stat_productivity_label: "năng suất cao hơn",
    cost_stat_savings: "70",
    cost_stat_savings_label: "tiết kiệm chi phí",
    cost_stats_note: "Số liệu tham chiếu từ nghiên cứu thị trường legal tech.",
    pricing_section_title: "Bảng giá",
    pricing_section_subtitle: "Chọn gói phù hợp với nhu cầu của bạn. Nâng cấp bất cứ lúc nào.",
    payment_billing_monthly: "Tháng",
    payment_billing_yearly: "Năm",
    pricing_no_monthly_plans: "Chưa có gói theo tháng.",
    pricing_no_yearly_plans: "Chưa có gói theo năm.",
    contact_modal_title: "Đặt lịch tư vấn miễn phí",
    contact_modal_subtitle: "Đặt lịch tư vấn 1-1 về giải pháp Lawzy và nhận báo giá phù hợp với doanh nghiệp của bạn.",
    contact_modal_benefit_1: "Phản hồi trong 24 giờ",
    contact_modal_benefit_2: "Tư vấn miễn phí, không ràng buộc",
    contact_modal_close: "Đóng",
    contact_modal_success: "Gửi thành công!",
    contact_modal_success_desc: "Chúng tôi sẽ liên hệ bạn trong thời gian sớm nhất.",
    contact_modal_error: "Có lỗi xảy ra. Vui lòng thử lại.",
    contact_modal_retry: "Thử lại",
    contact_modal_name: "Họ tên",
    contact_modal_name_placeholder: "Nguyễn Văn A",
    contact_modal_email: "Email",
    contact_modal_email_placeholder: "email@company.com",
    contact_modal_phone: "Số điện thoại",
    contact_modal_phone_placeholder: "+84",
    contact_modal_company: "Công ty",
    contact_modal_company_placeholder: "Công ty cổ phần Lawzy",
    contact_modal_message: "Nội dung",
    contact_modal_message_placeholder: "Bạn cần hỗ trợ gì?",
    contact_modal_submit: "Đặt lịch ngay",
    contact_modal_cancel: "Hủy",
    contact_modal_sending: "Đang gửi...",
    contact_validation_name: "Vui lòng nhập họ tên (ít nhất 2 ký tự)",
    contact_validation_email: "Vui lòng nhập email",
    contact_validation_email_invalid: "Vui lòng nhập đúng định dạng email",
    contact_validation_phone: "Vui lòng nhập số điện thoại hợp lệ",
    floating_back_to_top: "Về đầu trang",
    floating_book_demo: "Đặt lịch demo",
    contact_page_title: "Liên hệ Lawzy",
    contact_page_subtitle: "Để lại thông tin, đội ngũ chúng tôi sẽ phản hồi trong thời gian sớm nhất.",
    contact_page_back: "Về trang chủ",
    contact_page_note: "Chúng tôi cam kết phản hồi trong vòng 24 giờ làm việc.",
  },
  en: {
    nav_features: "Features",
    nav_pricing: "Pricing",
    nav_target: "Target",
    nav_team: "Team",
    nav_achievement: "Achievements",
    nav_contact: "Contact",
    nav_newspaper: "Press",
    nav_cost: "Cost savings",
    nav_menu: "Navigation menu",
    nav_dashboard: "Dashboard",
    nav_user: "Account",
    settings_title: "Settings",
    auth_logout: "Log out",
    try_free: "Try for free",
    contact_sales: "Contact sales",
    login: "Log in",
    survey_modal_title: "Register for Lawzy early access",
    survey_close: "Close form",
    survey_loading: "Preparing the form...",
    hero_badge: "Free $20 Lawzy AI credit for the first 100 users",
    hero_title_1: "AI-powered contract platform",
    hero_title_2: "for growth-focused teams",
    hero_title_2_options: "for growth-focused teams|for individuals|for legal teams|for startups",
    hero_subtitle: "Intelligence built in. Draft faster, spot risks early, and manage every contract in one place.",
    hero_cta_hint: "No credit card required. Get started in seconds.",
    hero_trust: "Trusted by press & partners",
    features_title: "Features that make you work smarter",
    features_title_highlight: "smarter",
    features_subtitle: "From drafting to signing. AI at every step. Reduce risk, increase efficiency.",
    feature_card1_title: "Draft contracts effortlessly",
    feature_card1_desc: "Create professional contracts in minutes with ready-made templates and smart AI suggestions.",
    feature_card2_title: "Automated risk review",
    feature_card2_desc: "AI analyzes and flags unfavorable clauses, helping you sign with confidence.",
    feature_card3_title: "Centralized contract management",
    feature_card3_desc: "Track status, get obligation reminders, and store all your contracts securely.",
    target_title: "For individuals, for teams, for companies",
    target_title_highlight: "individuals",
    target_subtitle: "From startups to enterprises, freelancers to legal departments. Lawzy helps everyone sign with confidence.",
    target_sme_title: "SMEs & Startups",
    target_sme_desc: "Optimize processes, reduce legal costs, and manage contracts effectively without a dedicated legal department.",
    target_sme_feat1: "Save on lawyer fees",
    target_sme_feat2: "Minimize legal risks",
    target_sme_feat3: "Centralized management, easy lookup",
    target_legal_title: "Legal Teams & HR",
    target_legal_desc: "A powerful tool to speed up review, standardize processes, and reduce repetitive workload.",
    target_legal_feat1: "Automated contract review",
    target_legal_feat2: "Standardize contract templates",
    target_legal_feat3: "Increase productivity",
    achievement_title: "Recognized",
    achievement_title_highlight: "Recognized",
    achievement_item_title: "2nd Prize - Startup & Innovation Competition HCMC 2025",
    members_title: "Our Team",
    member_thu_role: "Leader / Product Manager",
    member_quan_ly_role: "Software Developer",
    member_quan_huynh_role: "Software Developer",
    newspaper_title: "Lawzy in the press",
    newspaper_title_highlight: "Lawzy",
    blog_section_title: "News & Articles",
    blog_section_subtitle: "Latest news, legal insights and updates from Lawzy",
    blog_view_all: "View all",
    incubation_by: "Incubated by",
    footer_contact: "Contact",
    footer_tagline: "Peace of mind. On time. By your side",
    footer_description: "Draft, review, and manage contracts with AI. Built for businesses and legal teams.",
    footer_column_product: "Product",
    footer_column_legal: "Legal",
    footer_link_features: "Features",
    footer_link_pricing: "Pricing",
    footer_link_cost: "Cost savings",
    footer_link_audience: "Who it's for",
    footer_link_press: "Press",
    footer_link_achievements: "Achievements",
    footer_link_news: "News",
    footer_register: "Sign up",
    footer_address: "Ho Chi Minh City, Vietnam",
    footer_rights: "All rights reserved.",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Use",
    language_english: "EN",
    language_vietnamese: "VI",
    cost_title: "Fewer tools, fewer costs",
    cost_title_highlight: "fewer costs",
    cost_subtitle: "Cut software bloat. Keep teams fast, clear, and connected.",
    cost_stat_efficiency: "10",
    cost_stat_efficiency_label: "operational efficiency",
    cost_stat_productivity: "39",
    cost_stat_productivity_label: "more productive",
    cost_stat_savings: "70",
    cost_stat_savings_label: "cost savings",
    cost_stats_note: "Reference figures from legal tech market research.",
    pricing_section_title: "Pricing",
    pricing_section_subtitle: "Choose the plan that fits your needs. Upgrade anytime.",
    payment_billing_monthly: "Monthly",
    payment_billing_yearly: "Yearly",
    pricing_no_monthly_plans: "No monthly plans available.",
    pricing_no_yearly_plans: "No yearly plans available.",
    contact_modal_title: "Book a demo",
    contact_modal_subtitle: "Schedule a 1:1 consultation on Lawzy and receive a tailored quote for your business.",
    contact_modal_benefit_1: "Response within 24 hours",
    contact_modal_benefit_2: "Free, no-obligation consultation",
    contact_modal_close: "Close",
    contact_modal_success: "Sent successfully!",
    contact_modal_success_desc: "We will contact you as soon as possible.",
    contact_modal_error: "Something went wrong. Please try again.",
    contact_modal_retry: "Retry",
    contact_modal_name: "Full name",
    contact_modal_name_placeholder: "John Doe",
    contact_modal_email: "Email",
    contact_modal_email_placeholder: "email@company.com",
    contact_modal_phone: "Phone",
    contact_modal_phone_placeholder: "+84",
    contact_modal_company: "Company",
    contact_modal_company_placeholder: "Lawzy Inc.",
    contact_modal_message: "Message",
    contact_modal_message_placeholder: "What do you need help with?",
    contact_modal_submit: "Book now",
    contact_modal_cancel: "Cancel",
    contact_modal_sending: "Sending...",
    contact_validation_name: "Please enter your full name (at least 2 characters)",
    contact_validation_email: "Please enter your email",
    contact_validation_email_invalid: "Please enter a valid email address",
    contact_validation_phone: "Please enter a valid phone number",
    floating_back_to_top: "Back to top",
    floating_book_demo: "Book a demo",
    contact_page_title: "Contact Lawzy",
    contact_page_subtitle: "Leave your details and our team will get back to you as soon as possible.",
    contact_page_back: "Back to home",
    contact_page_note: "We aim to respond within 24 business hours.",
  },
};

type I18nContextValue = {
  locale: Locale;
  t: (key: string) => string;
  setLocale: (locale: Locale) => void;
};

const I18nContext = createContext<I18nContextValue | null>(null);

export function LandingLanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("lawzy_lang") as Locale | null;
      if (stored === "en" || stored === "vi") return stored;
      return navigator.language.startsWith("vi") ? "vi" : "en";
    }
    return "vi";
  });

  const t = useCallback(
    (key: string) => messages[locale][key] ?? key,
    [locale]
  );

  const setLocale = useCallback((next: Locale) => {
    if (typeof window !== "undefined") localStorage.setItem("lawzy_lang", next);
    setLocaleState(next);
  }, []);

  const value = useMemo(() => ({ locale, t, setLocale }), [locale, t, setLocale]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const ctx = useContext(I18nContext);
  if (!ctx) throw new Error("useI18n must be used within LandingLanguageProvider");
  return ctx;
}
